export enum GAME_TYPES {
    SET_POSITION = 'SET_POSITION',
    SET_ACTIVE_BONUSE = 'SET_ACTIVE_BONUSE',
    SET_WIN = 'SET_WIN',
    SET_CRYSTAL_COUNT = 'SET_CRYSTAL_COUNT',
    SET_FUEL_COUNT = 'SET_FUEL_COUNT',
    SET_GAME_START = 'SET_GAME_START'
}